nelmio_cors:
    defaults:
        allow_origin: ['*']
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization', 'X-Request-Id']
        expose_headers: ['Link', 'X-Request-Id']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['*']
